### ISSUE TITLE
Unable to access most of the attributes for templates

### ISSUE THREAD

**Issue by rpitera** [ntilley905/faastatus#1]
Home Assistant ver - 0.105.
faastatus ver - 0.01

While attributes unit_of_measurement, friendly_name and icon render correctly in templates none of the other attributes do.

Example: 
template `{{ states.sensor.newark_liberty_intl.attributes.ground_delay }}` doesn't produce any output at all.  The same for any other attribute except the three listed above.

Expected behavior:
Template `{{ states.sensor.newark_liberty_intl.attributes.ground_delay }}` should render either true or false.

This would allow users to build conditional displays as well as displaying the values of the attributes.

**Comment by ntilley905** [comment]
Thanks for the report! I have an idea about what might be causing it but won’t be able to get to it for a few days. In the mean time, try the template below and see if that gives you the result you need. 

`{{ state_attr("sensor.newark_liberty_intl", "Ground Delay") }}`

**Comment by rpitera** [comment]
Awesome, talk about a fast response!  And that does work for me.  BTW, I'm the guy on reddit that mentioned that this would be good for people who travel a lot like the core devs.  I installed it today and wanted to build a set of conditionals to display the attributes using Thomas Loven's template-entity-row plugin.

I'll be glad to share what I build if you want to use it as an example, but we'll wait until the bug is fixed as I imagine it will change things.  However I plan I setting it up later in the day with the workaround you provided.

Thanks!

**Comment by ntilley905** [comment]
This should be fixed in v0.1.1!
