### ISSUE TITLE
Uncaught instance in data?  

### ISSUE THREAD

**Issue by rpitera** [ntilley905/faastatus#3]
Might be a bug here; state shows two delay count but I'm only seeing one attribute triggered as true.  

![faastatus](https://user-images.githubusercontent.com/19910294/74257870-6ed4e080-4cc3-11ea-9683-dc9417d284bc.png)

So I took a look at the status on FAA site and I see there is a delay by destination instance.  Not sure if that one is important to you but thought I'd mention it as it does alter the state count.

![faa_site](https://user-images.githubusercontent.com/19910294/74258326-24a02f00-4cc4-11ea-8b4b-da43bbf2dfa6.png)

**Comment by rpitera** [comment]
Don't hate me.  LOL

**Comment by ntilley905** [comment]
Huh, weird! Is there anything related in your logs? Can you try forcing the sensor to update and see if that solves it? Either way, definitely another bug! And don't be sorry, you're giving me stuff to do!

To force the update go to the services panel in developer tools and call the`homeassistant.update_entity` service with the entity_id of the sensor.

**Comment by ntilley905** [comment]
Yep, added Newark to my own config and I’m having the same issue. Hmm...

**Comment by ntilley905** [comment]
Fixed in v0.1.2, should be available on HACS now! In changing the cases to fix the attributes in v0.1.1 I accidentally created a bug by changing “Ground Delay” to “ground Delay.” Good catch!

**Comment by rpitera** [comment]
Cool, glad to help.  I was thinking - "This guy is going to be sick of me pretty soon..." LOL

**Comment by ntilley905** [comment]
Honestly the more bugs you can find the better! Especially ones that I can fix with less than 10 minutes of work haha!

**Comment by rpitera** [comment]
Works for me.  I'll keep my eyes open.  I'm not a coder so this is the way I contribute!
